spring.application.name=Import_Product_using_CSV


spring.batch.job.enabled=false


kibo.clientId=gaurav_test_app
kibo.clientSecret=dc7ca79c0e854c82a5399b3add11a48f
kibo.tenantId=52898
kibo.siteId=77852
kibo.tenantHost=t52898.sandbox.mozu.com
kibo.homeHost=home.mozu.com

